/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        sentinel: {
          bg: 'var(--sentinel-bg)',
          surface: 'var(--sentinel-surface)',
          'surface-alt': 'var(--sentinel-surface-alt)',
          border: 'var(--sentinel-border)',
          'border-strong': 'var(--sentinel-border-strong)',
          text: 'var(--sentinel-text)',
          'text-secondary': 'var(--sentinel-text-secondary)',
          'text-muted': 'var(--sentinel-text-muted)',
          teal: 'var(--sentinel-teal)',
          'teal-light': 'var(--sentinel-teal-light)',
          'teal-dark': 'var(--sentinel-teal-dark)',
          amber: 'var(--sentinel-amber)',
          'amber-light': 'var(--sentinel-amber-light)',
          'amber-dark': 'var(--sentinel-amber-dark)',
          red: 'var(--sentinel-red)',
          'red-light': 'var(--sentinel-red-light)',
          'red-dark': 'var(--sentinel-red-dark)',
          green: 'var(--sentinel-green)',
          'green-light': 'var(--sentinel-green-light)',
          'green-dark': 'var(--sentinel-green-dark)',
          blue: 'var(--sentinel-blue)',
          'blue-light': 'var(--sentinel-blue-light)',
          'blue-dark': 'var(--sentinel-blue-dark)',
          rose: 'var(--sentinel-rose)',
          'rose-light': 'var(--sentinel-rose-light)',
          'rose-dark': 'var(--sentinel-rose-dark)',
          violet: 'var(--sentinel-violet)',
          'violet-light': 'var(--sentinel-violet-light)',
          'violet-dark': 'var(--sentinel-violet-dark)',
          orange: 'var(--sentinel-orange)',
          'orange-light': 'var(--sentinel-orange-light)',
          'orange-dark': 'var(--sentinel-orange-dark)',
          cyan: 'var(--sentinel-cyan)',
          'cyan-light': 'var(--sentinel-cyan-light)',
          'cyan-dark': 'var(--sentinel-cyan-dark)',
        },
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      borderRadius: {
        'xl2': '16px',
      },
    },
  },
  plugins: [],
};
